In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./dataset/matches_1930_2022.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    str
 1   away_team                        964 non-null    str
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    str
 9   home_captain                     644 non-null    str
 10  away_manager                     964 non-null    str
 11  away_captain                     644 non-null    str
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    str
 14  Officials                        709 non-null    str
 15  Round                            964 non-null    str
 16  Date                             964 non-null    str
 17  Score                            964 non-null    str
 18  Referee                          709 non-null    str
 19  Notes                            73 non-null     str
 20  Host                             964 non-null    str
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    str
 23  away_goal                        571 non-null    str
 24  home_goal_long                   718 non-null    str
 25  away_goal_long                   571 non-null    str
 26  home_own_goal                    39 non-null     str
 27  away_own_goal                    17 non-null     str
 28  home_penalty_goal                116 non-null    str
 29  away_penalty_goal                84 non-null     str
 30  home_penalty_miss_long           6 non-null      str
 31  away_penalty_miss_long           9 non-null      str
 32  home_penalty_shootout_goal_long  34 non-null     str
 33  away_penalty_shootout_goal_long  34 non-null     str
 34  home_penalty_shootout_miss_long  24 non-null     str
 35  away_penalty_shootout_miss_long  30 non-null     str
 36  home_red_card                    51 non-null     str
 37  away_red_card                    54 non-null     str
 38  home_yellow_red_card             23 non-null     str
 39  away_yellow_red_card             31 non-null     str
 40  home_yellow_card_long            621 non-null    str
 41  away_yellow_card_long            627 non-null    str
 42  home_substitute_in_long          740 non-null    str
 43  away_substitute_in_long          747 non-null    str
dtypes: float64(4), int64(4), str(36)
memory usage: 331.5 KB

In [4]:
df.head(5)

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

In [5]:
df.isnull().sum()

home_team                            0
away_team                            0
home_score                           0
home_xg                            836
home_penalty                       929
away_score                           0
away_xg                            836
away_penalty                       929
home_manager                         0
home_captain                       320
away_manager                         0
away_captain                       320
Attendance                           0
Venue                                0
Officials                          255
Round                                0
Date                                 0
Score                                0
Referee                            255
Notes                              891
Host                                 0
Year                                 0
home_goal                          246
away_goal                          393
home_goal_long                     246
away_goal_long                     393
home_own_goal                      925
away_own_goal                      947
home_penalty_goal                  848
away_penalty_goal                  880
home_penalty_miss_long             958
away_penalty_miss_long             955
home_penalty_shootout_goal_long    930
away_penalty_shootout_goal_long    930
home_penalty_shootout_miss_long    940
away_penalty_shootout_miss_long    934
home_red_card                      913
away_red_card                      910
home_yellow_red_card               941
away_yellow_red_card               933
home_yellow_card_long              343
away_yellow_card_long              337
home_substitute_in_long            224
away_substitute_in_long            217
dtype: int64

In [6]:
columns_needed = [
    'home_team',
    'away_team',
    'home_score',
    'away_score',
    'Year',
    'Round',
    'Attendance',
    'Venue',
    'Date'
]

matches = df[columns_needed].copy()

In [7]:
matches.drop_duplicates(inplace=True)

In [8]:
matches['Date'] = pd.to_datetime(matches['Date'])

In [9]:
matches.isnull().sum()

home_team     0
away_team     0
home_score    0
away_score    0
Year          0
Round         0
Attendance    0
Venue         0
Date          0
dtype: int64

In [10]:
def get_result(row):
    if row['home_score'] > row['away_score']:
        return 'Home Win'
    elif row['home_score'] < row['away_score']:
        return 'Away Win'
    else:
        return 'Draw'

matches['result'] = matches.apply(get_result, axis=1)

In [11]:
home_df = pd.DataFrame({
    'team': matches['home_team'],
    'opponent': matches['away_team'],
    'goals_for': matches['home_score'],
    'goals_against': matches['away_score'],
    'year': matches['Year'],
    'round': matches['Round'],
    'attendance': matches['Attendance']
})

In [12]:
home_df['win'] = (home_df['goals_for'] > home_df['goals_against']).astype(int)

home_df['draw'] = (home_df['goals_for'] == home_df['goals_against']).astype(int)

home_df['loss'] = (home_df['goals_for'] < home_df['goals_against']).astype(int)

In [13]:
away_df = pd.DataFrame({
    'team': matches['away_team'],
    'opponent': matches['home_team'],
    'goals_for': matches['away_score'],
    'goals_against': matches['home_score'],
    'year': matches['Year'],
    'round': matches['Round'],
    'attendance': matches['Attendance']
})

In [14]:
away_df['win'] = (away_df['goals_for'] > away_df['goals_against']).astype(int)

away_df['draw'] = (away_df['goals_for'] == away_df['goals_against']).astype(int)

away_df['loss'] = (away_df['goals_for'] < away_df['goals_against']).astype(int)

In [15]:
teams = pd.concat([home_df, away_df], ignore_index=True)

In [16]:
teams.head()

,team,opponent,goals_for,goals_against,year,round,attendance,win,draw,loss
0,Argentina,France,3,3,2022,Final,88966,0,1,0
1,Croatia,Morocco,2,1,2022,Third-place match,44137,1,0,0
2,France,Morocco,2,0,2022,Semi-finals,68294,1,0,0
3,Argentina,Croatia,3,0,2022,Semi-finals,88966,1,0,0
4,Morocco,Portugal,1,0,2022,Quarter-finals,44198,1,0,0

In [17]:
team_stats = teams.groupby('team').agg(
    matches_played=('team', 'count'),
    wins=('win', 'sum'),
    draws=('draw', 'sum'),
    losses=('loss', 'sum'),
    goals_scored=('goals_for', 'sum'),
    goals_conceded=('goals_against', 'sum'),
    avg_attendance=('attendance', 'mean')
)

In [18]:
team_stats['goal_difference'] = (
    team_stats['goals_scored'] - team_stats['goals_conceded']
)

In [19]:
team_stats['win_percentage'] = (
    team_stats['wins'] / team_stats['matches_played'] * 100
).round(2)

In [20]:
teams['goal_margin'] = (
    teams['goals_for'] - teams['goals_against']
)

In [21]:
biggest_win = teams.loc[
    teams.groupby('team')['goal_margin'].idxmax(),
    ['team', 'opponent', 'goals_for', 'goals_against', 'goal_margin']
]

In [22]:
biggest_loss = teams.loc[
    teams.groupby('team')['goal_margin'].idxmin(),
    ['team', 'opponent', 'goals_for', 'goals_against', 'goal_margin']
]

In [23]:
most_goals = teams.groupby('team')['goals_for'].max()

In [24]:
teams['clean_sheet'] = (
    teams['goals_against'] == 0
).astype(int)

clean_sheets = teams.groupby('team')['clean_sheet'].sum()

In [25]:
appearances = teams.groupby('team')['year'].nunique()

In [26]:
team_stats['clean_sheets'] = clean_sheets

team_stats['appearances'] = appearances

team_stats['most_goals_in_match'] = most_goals

In [27]:
team_stats.sort_values('wins', ascending=False).head(10)

,matches_played,wins,draws,losses,goals_scored,goals_conceded,avg_attendance,goal_difference,win_percentage,clean_sheets,appearances,most_goals_in_match
team,,,,,,,,,,,,
Brazil,114,76,19,19,237,108,54806.131579,129,66.67,48,22,7
Argentina,88,47,17,24,152,101,54208.306818,51,53.41,31,18,6
Italy,83,45,21,17,128,77,50856.674699,51,54.22,30,18,7
France,73,39,14,20,136,85,46944.109589,51,53.42,24,16,7
Germany,56,37,7,12,126,67,48944.982143,59,66.07,19,11,8
England,74,32,22,20,104,68,48404.054054,36,43.24,36,16,6
West Germany,56,31,14,11,106,63,54201.339286,43,55.36,22,9,6
Spain,67,31,17,19,108,75,45477.447761,33,46.27,22,16,7
Netherlands,55,30,14,11,96,52,53023.963636,44,54.55,21,11,5
Uruguay,59,25,13,21,89,76,44295.338983,13,42.37,23,14,8

In [28]:
team_stats.sort_values('goals_scored', ascending=False).head(10)

,matches_played,wins,draws,losses,goals_scored,goals_conceded,avg_attendance,goal_difference,win_percentage,clean_sheets,appearances,most_goals_in_match
team,,,,,,,,,,,,
Brazil,114,76,19,19,237,108,54806.131579,129,66.67,48,22,7
Argentina,88,47,17,24,152,101,54208.306818,51,53.41,31,18,6
France,73,39,14,20,136,85,46944.109589,51,53.42,24,16,7
Italy,83,45,21,17,128,77,50856.674699,51,54.22,30,18,7
Germany,56,37,7,12,126,67,48944.982143,59,66.07,19,11,8
Spain,67,31,17,19,108,75,45477.447761,33,46.27,22,16,7
West Germany,56,31,14,11,106,63,54201.339286,43,55.36,22,9,6
England,74,32,22,20,104,68,48404.054054,36,43.24,36,16,6
Netherlands,55,30,14,11,96,52,53023.963636,44,54.55,21,11,5
Uruguay,59,25,13,21,89,76,44295.338983,13,42.37,23,14,8

In [29]:
team_stats.sort_values(
    'win_percentage',
    ascending=False
).head(10)

,matches_played,wins,draws,losses,goals_scored,goals_conceded,avg_attendance,goal_difference,win_percentage,clean_sheets,appearances,most_goals_in_match
team,,,,,,,,,,,,
Brazil,114,76,19,19,237,108,54806.131579,129,66.67,48,22,7
Germany,56,37,7,12,126,67,48944.982143,59,66.07,19,11,8
West Germany,56,31,14,11,106,63,54201.339286,43,55.36,22,9,6
Netherlands,55,30,14,11,96,52,53023.963636,44,54.55,21,11,5
Italy,83,45,21,17,128,77,50856.674699,51,54.22,30,18,7
France,73,39,14,20,136,85,46944.109589,51,53.42,24,16,7
Argentina,88,47,17,24,152,101,54208.306818,51,53.41,31,18,6
FR Yugoslavia,4,2,1,1,5,4,37193.750000,1,50.00,2,1,2
Türkiye,10,5,1,4,20,17,38318.600000,3,50.00,4,2,7
Portugal,35,17,6,12,61,41,50799.514286,20,48.57,12,8,7